# Generated by Django 4.2.3 on 2023-09-23 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(help_text='Required', max_length=255, verbose_name='Image title'),
        ),
        migrations.AlterField(
            model_name='imagesize',
            name='width',
            field=models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Image width, px'),
        ),
    ]
